# General Settings
num_workers: 4
seed: 42          # Seed for all random-based function calls
log_level: INFO
device: cuda      # 'cuda' if torch.cuda.is_available() else 'cpu'

# Data Settings
data_dir: output/data
datasets: 
  # - 'tqa_gen'
  # - 'halueval'
  # - 'halubench'
  - 'felm'
  # - 'defan'
  # - 'simpleqa'
  
# Control Settings
debug_mode: true             # Debug mode
n_pds: 5                     # Number of datapoints to sample for debugging
gen_anlyz_figs: false
gen_sent_embeds: true
save_full_data: true
save_basic_stats: true
remove_duplicates: true
sent_sim_metric: 'bleu'

# kwargs

# clustering
clustering_algo: dbscan # dbscan

# Model Settings
sentence_embedder: sentence-transformers/all-MiniLM-L6-v2  # HuggingFace or local path
